version: "3.3"

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-fpm_${APP_NAME}
        restart: unless-stopped
        tty: true
        ports:
            - "9000:9000"
        volumes:
            - ../../${APP_NAME}:/var/www/html
        networks:
            - pcg

    nginx:
        image: nginx:1.21.5-alpine
        container_name: nginx_${APP_NAME}
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../../${APP_NAME}:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - pcg

    redis:
        image: redis:alpine3.15
        container_name: redis_${APP_NAME}
        restart: unless-stopped
        tty: true
        ports:
            - 6379:6379
        networks:
            - pcg

    mysql:
        image: mysql:8.0.28-oracle
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: RpwiN9569
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
        container_name: mysql_${APP_NAME}
        restart: unless-stopped
        tty: true
        volumes:
            - E:\mysql\data:/var/lib/mysql
        ports:
            - 3306:3306
        networks:
            - pcg

    phpmyadmin:
        container_name: phpmyadmin_${APP_NAME}
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        links:
            - mysql
        ports:
            - 8081:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_PORT=3306
        networks:
            - pcg
networks:
    pcg:
        driver: bridge
